@startuml

@startuml
Title CARPORT

State custermorpage.jsp
State employeepage.jsp
State index.jsp
State loginpage.jsp
State receiptpage.jsp
State registerpage.jsp
State materialpage.jsp
State showcarportrequestpage.jsp

[*] -> index.jsp
index.jsp --> receiptpage.jsp

employeepage.jsp --> showcarportrequestpage.jsp
@enduml